version: '2'
services:
  web:
    image: node:latest
    ports:
      - "3000:3000"
      - "127.0.0.1:9229:9229"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    links:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./docker/mongo/db:/data/db
    ports:
      - 27017:27017
